spring:

  application:
    name: "hh-bot"

  profiles:
    active: local

  datasource:
    username: postgres
    password: ${db-password}
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: hh-bot

    user: postgres
    password: ${db-password}
    url: jdbc:postgresql://localhost:5432/postgres



hh:
  base-url: "https://api.hh.ru"
  header-name: "User-Agent"
  header-value: "Hh-bot/1.0 (noleg867@gmail.com)"


telegram:
  token: ${secret-token}